<?xml version="1.0" encoding="utf-8"?>
<!--
	beachholiday.html
	Purpose:To introuce a XML file
	Author:Haowen Wang
	Id:c3335454
	Date 20/9/2020
-->
<?xml-stylesheet type="text/xsl" href="holiday.xsl"?>
<!DOCTYPE holidays [
	<!ELEMENT holidays (holiday*)>
	<!ELEMENT holiday (packagename,Description,cost,nights,popularity,AccommodationOptions+,CouponCode?,reviews?,picture+,URL,eatinghabit?,language)>
	<!ELEMENT packagename (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT cost (#PCDATA)>
	<!ELEMENT nights (#PCDATA)>
	<!ELEMENT popularity (#PCDATA)>
	<!ELEMENT AccommodationOptions (Location,Additionalcost)>
	<!ELEMENT Location (#PCDATA)>
	<!ELEMENT Additionalcost (#PCDATA)>
	<!ELEMENT CouponCode (#PCDATA)>
	<!ELEMENT reviews (#PCDATA)>
	<!ELEMENT picture (#PCDATA)>
	<!ELEMENT URL (#PCDATA)>
	<!ELEMENT eatinghabit (#PCDATA)>
	<!ELEMENT language (#PCDATA)>
	<!ATTLIST packagename id CDATA #REQUIRED>
]>

<holidays>
	<holiday>
		<packagename id="001">Tanjung Lesung, The Place to Layback and Immerse in the Beauty of Nature</packagename>
		<Description>Located on Java’s most western coast in the district of Pandeglang in the province of Banten, the Tanjung Lesung resembles the Lesung, which in the local Sundanese language means the receptacle for rice pounding. Tanjung Lesung is a developing integrated beach resort for recreation and hotels overlooking Mt Anak Krakatu, all that is left of the once-mighty Krakatau volcano. This huge 1,500 hectares area of Tanjung Lesung has been developed by the Banten West Java Tourism Development Corporation (BWJ) since 1996, patterned after the famed Nusa Dua Resort in Bali. The resort is envisaged to contain top range hotels and restaurants, a convention hall, a number of golf courses, marina and theme park.</Description>
		<cost>1800 dollars</cost>
		<nights>3</nights>
		<popularity>4.5 stars</popularity>
		<AccommodationOptions>
			<Location>Tanjung Lesung</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>001.jpg</picture>
		<URL>https://www.indonesia.travel/sg/en/destinations/java/serang/tanjung-lesung</URL>
		<eatinghabit>Indonesia is located in the tropics and does not produce wheat, so the staple food of residents is rice, corn or potatoes, especially rice is more common. In addition to cooking rice, Indonesians like to use banana leaves or palm leaves to wrap rice or glutinous rice in a diamond shape and steam it. It is called "Keduba". However, Indonesians also like to eat noodles, such as noodles and bread.</eatinghabit>
		<language>Bahasa Indonesia</language>
	</holiday>

	<holiday>
		<packagename id="002">Sawarna Beach, The Truly Captivating Beach on The South Coast of Java</packagename>
		<Description>The tourism village of Sawarna is the entry point to this natural wonder. As you enter the village, you will be greeted by lush green paddy fields, serene village ambiance, and refreshing breezes. Sawarna Beach is located at Gendol, Bayah District, Lebak Regency, in the province of Banten, Jakarta's neighbor to the capital's west. Sawarna Beach offers a host of natural wonders such as asits rushing river, lush forest, rocky hills, caves, and more. The beautiful landscape is also shrouded in the myth of “Nyi Roro Kidul”, the mythical Queen of the South Seas, besides being replete with the history of coal exploitation in the nearby areas of Bayah and Lebak.</Description>
		<cost>1600 dollars</cost>
		<nights>3</nights>
		<popularity>4.4 stars</popularity>
		<AccommodationOptions>
			<Location>Sawarna Beach</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>002.jpg</picture>
		<URL>https://www.indonesia.travel/sg/en/destinations/java/serang/sawarna-beach</URL>
		<eatinghabit>Indonesia is located in the tropics and does not produce wheat, so the staple food of residents is rice, corn or potatoes, especially rice is more common. In addition to cooking rice, Indonesians like to use banana leaves or palm leaves to wrap rice or glutinous rice in a diamond shape and steam it. It is called "Keduba". However, Indonesians also like to eat noodles, such as noodles and bread.</eatinghabit>
		<language>Bahasa Indonesia</language>
	</holiday>

	<holiday>
		<packagename id="003">Parangtritis, a Mystical and Enchanting Beach in Yogyakarta</packagename>
		<Description>Parangtritis is located around 28 km (17 miles) from Yogyakarta this is the ideal distance to come for a day trip to take a break out of the city and soak up the roar of the waves and the astounding atmosphere. Here you’ll see some incredibly green lush hills set against the backdrop of a raging ocean.</Description>
		<cost>2000 dollars</cost>
		<nights>4</nights>
		<popularity>4.5 stars</popularity>
		<AccommodationOptions>
			<Location>Yogyakarta</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>003.jpg</picture>
		<URL>https://www.indonesia.travel/sg/en/destinations/java/yogyakarta/parangtritis-beach</URL>
		<eatinghabit>Indonesia is located in the tropics and does not produce wheat, so the staple food of residents is rice, corn or potatoes, especially rice is more common. In addition to cooking rice, Indonesians like to use banana leaves or palm leaves to wrap rice or glutinous rice in a diamond shape and steam it. It is called "Keduba". However, Indonesians also like to eat noodles, such as noodles and bread.</eatinghabit>
		<language>Bahasa Indonesia</language>
	</holiday>
</holidays>

