<?xml version="1.0" encoding="utf-8"?>
<!--
	luxuryholidays.html
	Purpose:To introuce a XML file
	Author:Haowen Wang
	Id:c3335454
	Date 20/9/2020
-->
<?xml-stylesheet type="text/xsl" href="holiday.xsl"?>
<!DOCTYPE holidays [
	<!ELEMENT holiday (packagename,Description,cost,nights,popularity,AccommodationOptions+,CouponCode?,reviews?,picture+,URL,eatinghabit?,language)>
	<!ELEMENT packagename (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT cost (#PCDATA)>
	<!ELEMENT nights (#PCDATA)>
	<!ELEMENT popularity (#PCDATA)>
	<!ELEMENT AccommodationOptions (Location,Additionalcost)>
	<!ELEMENT Location (#PCDATA)>
	<!ELEMENT Additionalcost (#PCDATA)>
	<!ELEMENT CouponCode (#PCDATA)>
	<!ELEMENT reviews (#PCDATA)>
	<!ELEMENT picture (#PCDATA)>
	<!ELEMENT URL (#PCDATA)>
	<!ELEMENT eatinghabit (#PCDATA)>
	<!ELEMENT language (#PCDATA)>
	<!ATTLIST packagename id CDATA #REQUIRED>
]>

<holidays>
	<holiday>
		<packagename id="004">Mauritius all inclusive holidays</packagename>
		<Description>The pure white sands, sparkling turquoise waters and luxury beachfront retreats on Mauritius rival some of the best in the world. There are world-class golf courses, pretty towns showcasing Creole architecture, and, away from the coast, cascading waterfalls, virgin forests and botanical gardens</Description>
		<cost>3000 dollars</cost>
		<nights>4</nights>
		<popularity>4.9 stars</popularity>
		<AccommodationOptions>
			<Location>Mauritius</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>004.jpg</picture>
		<URL>https://www.kuoni.co.uk/mauritius/mauritius-all-inclusive-holidays</URL>
		<eatinghabit>Due to the mixed ethnicity and cultural diversity, the food of Mauritius is also influenced by Creole, Chinese, European and Indian cuisine, so a meal often mixes different local dishes.</eatinghabit>
		<language>English</language>
	</holiday>
	
	<holiday>
		<packagename id="005">Sri Lanka all inclusive holidays</packagename>
		<Description> On a stunning coconut-fringed coastline lapped by the Indian Ocean, the tiny tear drop shaped island of Sri Lanka lies just beneath India and is surrounded by natural beauty, friendly people, sacred Buddhist temples and emerald green paddy fields. If you’re thinking about a Sri Lanka holiday it’s well worth going all inclusive. Many of the hotels are set within pretty but tiny villages, beachfront, on tea plantations or in verdant forest, and often, there’s not that many places to eat and drink outside of your hotel. Known as the ‘pearl of the Indian Ocean’ you’ll certainly want to get out and explore the lush rainforests, golden beaches and national parks, so an all-inclusive package means you also have plenty of time to hang out at the pool bar and enjoy wallet-free dining and drinks too.</Description>
		<cost>4500 dollars</cost>
		<nights>4</nights>
		<popularity>4.4 stars</popularity>
		<AccommodationOptions>
			<Location>Sri Lanka</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>005.jpg</picture>
		<URL>https://www.kuoni.co.uk/sri-lanka/sri-lanka-all-inclusive-holidays</URL>
		<eatinghabit>The Sri Lankan diet is similar to the Indian diet. It is based on rice, and likes to eat chicken, which has a strong taste. He likes to add curry, chili, coconut oil and other spices to various dishes. The taste is spicy and strong, especially red pepper, which is a seasoning. The most commonly used. Boiled rice is the most distinctive delicacy in Sri Lanka. Add the cleaned rice to a large earthen jar and add water to cook. The cooked rice is yellowish in color, which is easy to store and has the same fragrance for a long time. It can be eaten at any time.</eatinghabit>
		<language>Sinhala</language>
	</holiday>

	<holiday>
		<packagename id="006">All inclusive holidays to Europe</packagename>
		<Description>Whether it’s sun-kissed luxury in the Med, beach bliss on the Turquoise Coast or family fun on the Canary Islands, we offer a range of all-inclusive Europe holidays. Halkidiki’s IKOS Olivia is redefining European all-inclusive with its Infinite Lifestyle concept. Perfect for families wanting to take the worry out of totting up the dining and refreshment bill throughout the day, here, restaurants are overseen by Michelin-starred chefs, there are inclusions such as land and non-motorised watersports and an ongoing flow of ice-cream, sweets and pool service. Over on the island of Corfu, you can enjoy a similar experience at the newly opened IKOS Dassia. If you prefer your views to include the Mediterranean Sea as well as the mountains, Turkey’s Rixos Premium Gocek is a chic all-inclusive retreat right on the marina whilst the Hilton Daliman Sarigerme Resort  Spa offers one of the best luxury family-friendly resorts in Turkey</Description>
		<cost>5000 dollars</cost>
		<nights>4</nights>
		<popularity>4.7 stars</popularity>
		<AccommodationOptions>
			<Location>Europe</Location>
			<Additionalcost>200 dollars</Additionalcost>
		</AccommodationOptions>
		<reviews>Beautiful scenery, suitable for vacation</reviews>
		<picture>006.jpg</picture>
		<URL>https://www.kuoni.co.uk/europe/all-inclusive-holidays-to-europe</URL>
		<eatinghabit>Similar to Australia</eatinghabit>
		<language>English</language>
	</holiday>
</holidays>