<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE holidays [
	<!ELEMENT holiday (packagename,Description,cost,nights,popularity,AccommodationOptions+,CouponCode?,reviews?,picture+,URL,eatinghabit?,language)>
	<!ELEMENT packagename (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT cost (#PCDATA)>
	<!ELEMENT nights (#PCDATA)>
	<!ELEMENT popularity (#PCDATA)>
	<!ELEMENT AccommodationOptions (Location,Additionalcost)>
	<!ELEMENT Location (#PCDATA)>
	<!ELEMENT Additionalcost (#PCDATA)>
	<!ELEMENT CouponCode (#PCDATA)>
	<!ELEMENT reviews (#PCDATA)>
	<!ELEMENT picture (#PCDATA)>
	<!ELEMENT URL (#PCDATA)>
	<!ELEMENT eatinghabit (#PCDATA)>
	<!ELEMENT language (#PCDATA)>
	<!ATTLIST packagename id CDATA #REQUIRED>
]>

<holidays>
	<holiday>
		<packagename id="1">sample</Description>
		<cost>sample</cost>
		<nights>sample</nights>
		<popularity>sample</popularity>
		<AccommodationOptions>
			<Location>sample</Location>
			<Additionalcost>sample</Additionalcost>
		</AccommodationOptions>
		<reviews>sample</reviews>
		<picture>sample</picture>
		<URL>sample</URL>
		<eatinghabit>sample</eatinghabit>
		<language>sample</language>
	</holiday>
	
	<holiday>
		<packagename id="1">sample</Description>
		<cost>samplesamplesamplesamplesamplesamplesamplesamplesample</cost>
		<nights>samplesamplesamplesamplesamplesamplesamplesample</nights>
		<popularity>samplesamplesamplesamplesamplesamplesample</popularity>
		<AccommodationOptions>
			<Location>samplesamplesamplesamplesamplesample</Location>
			<Additionalcost>samplesamplesamplesamplesample</Additionalcost>
		</AccommodationOptions>
		<reviews>samplesamplesamplesample</reviews>
		<picture>samplesamplesample</picture>
		<URL>sample</URL>
		<eatinghabit>samplesample</eatinghabit>
		<language>sample</language>
	</holiday>

	<holiday>
		<packagename id="1">sample</Description>
		<cost>sample</cost>
		<nights>sample</nights>
		<popularity>sample</popularity>
		<AccommodationOptions>
			<Location>sample</Location>
			<Additionalcost>sample</Additionalcost>
		</AccommodationOptions>
		<reviews>sample</reviews>
		<picture>sample</picture>
		<URL>sample</URL>
		<eatinghabit>sample</eatinghabit>
		<language>sample</language>
	</holiday>
</holidays>